version: "3.3"

services:
  redis_channel:
    image: redis:alpine
  publisher:
    image: rohit20001221/zerodha_publisher
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    command: python manage.py runserver 0.0.0.0:80
  celery:
    image: rohit20001221/zerodha_publisher
    build: .
    volumes:
      - .:/app
    command: "celery -A bittrade worker -l INFO"
    depends_on:
      - redis_channel
