version: "3.3"

services:
  redis_channel:
    image: redis:alpine
  publisher:
    image: rohit20001221/zerodha_publisher
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: daphne autotrade_PublisherZerodha.asgi:application -b 0.0.0.0 -p 8000
