version: "3.3"

services:
  redis_channel:
    image: redis:alpine
  publisher:
    image: rohit20001221/zerodha_publisher
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    command: daphne bittrade.asgi:application -b 0.0.0.0
  celery:
    image: rohit20001221/zerodha_publisher
    build: .
    volumes:
      - .:/app
    command: "celery -A bittrade worker -l INFO -c 1"
    depends_on:
      - redis_channel
