version: "3.3"

services:
  redis_channel:
    image: redis:alpine
  publisher:
    image: rohit20001221/zerodha_publisher
    build: .
    volumes:
      - .:/app
      - static:/app/static
    command: daphne bittrade.asgi:application -b 0.0.0.0 -p 80
  nginx_server:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/app/static

volumes:
  static:
