name: CI to docker hub

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push bittrade
        id: docker_build_bittrade
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bittrade:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_bittrade.outputs.digest }}

      - name: Build and push bittrade_nginx
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bittrade_nginx:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_nginx.outputs.digest }}

      - name: Deploy the code
        id: digital_ocean_deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          PORT: ${{ secrets.DIGITAL_OCEAN_PORT }}
          KEY: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}
          script: sh /home/rohit/bittrade/deploy.sh
